### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by edjames** [tagomoris/fluent-helper-plugin-spec#1]
Hi

I'm busy writing some fluentd plugins and I want to have my tests in RSpec.
Is this repo still alive or has it been abandoned?

Any pointers for how you use this would b most welcome.

Thanks,
Ed.

**Comment by tagomoris** [comment]
Actually it's not alive.
I'm now planning to introduce new plugin test helper for Fluentd v0.14 APIs, based on `test-unit` version 3.

**Comment by edjames** [comment]
Ok, so would you recommend I stick with test-unit for testing my custom plugins?
Or is there a plan to also have RSpec support?

**Comment by tagomoris** [comment]
Fluentd core developer's decision is to use test-unit.
So, using test-unit is highly near from core plugin testing.

**Comment by edjames** [comment]
Ok, thanks very much for getting back to me so fast.
